# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 The Worx Company
# Author: Kurt Vanderwater <kurt@worxco.net>

#
# CloudFormation Template: Storage Infrastructure
#
# Purpose: Creates FSx for OpenZFS shared filesystem and S3 buckets
#
# Resources:
#   - FSx for OpenZFS (shared storage for /var/www across NGINX and PHP-FPM)
#   - S3 buckets (Drupal media uploads, backups, Image Builder scripts)
#   - SSM Parameters (FSx DNS name, S3 bucket names for easy reference)
#
# Dependencies: cf-vpc.yaml (subnets, security groups)
#
# Outputs: FSx file system ID/DNS, S3 bucket names
#

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Storage infrastructure - FSx OpenZFS and S3 buckets for scalable web hosting'

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name
    Default: production

  FSxStorageCapacityGB:
    Type: Number
    Description: FSx storage capacity in GB (minimum 64GB, scales automatically)
    MinValue: 64
    MaxValue: 524288
    Default: 100

  FSxThroughputMBps:
    Type: Number
    Description: FSx throughput capacity in MB/s
    AllowedValues: [64, 128, 256, 512, 1024, 2048, 3072, 4096]
    Default: 128

  FSxDeploymentType:
    Type: String
    Description: FSx deployment type (SINGLE_AZ_1 for dev/test, MULTI_AZ_1 for production)
    AllowedValues: [SINGLE_AZ_1, MULTI_AZ_1]
    Default: SINGLE_AZ_1

  FSxAutomaticBackupRetentionDays:
    Type: Number
    Description: Number of days to retain automatic backups
    MinValue: 0
    MaxValue: 90
    Default: 14

  EnableS3Versioning:
    Type: String
    Description: Enable versioning on S3 buckets
    AllowedValues: [true, false]
    Default: true

  BucketSuffix:
    Type: String
    Description: Unique suffix for S3 bucket names (ensures global uniqueness)
    AllowedPattern: '^[a-z0-9-]{4,12}$'
    ConstraintDescription: Must be 4-12 lowercase letters, numbers, or hyphens
    Default: change-me

Conditions:
  S3VersioningEnabled: !Equals [!Ref EnableS3Versioning, true]
  MultiAZDeployment: !Equals [!Ref FSxDeploymentType, MULTI_AZ_1]

Resources:
  # ========================================
  # FSx for OpenZFS File System
  # ========================================

  FSxFileSystem:
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: OPENZFS
      StorageCapacity: !Ref FSxStorageCapacityGB
      SubnetIds:
        - !If
          - MultiAZDeployment
          - Fn::ImportValue: !Sub '${EnvironmentName}-nginx-subnets'
          - !Select [0, !Split [',', Fn::ImportValue: !Sub '${EnvironmentName}-nginx-subnets']]
      SecurityGroupIds:
        - Fn::ImportValue: !Sub '${EnvironmentName}-fsx-sg-id'
      OpenZFSConfiguration:
        DeploymentType: !Ref FSxDeploymentType
        ThroughputCapacity: !Ref FSxThroughputMBps
        AutomaticBackupRetentionDays: !Ref FSxAutomaticBackupRetentionDays
        DailyAutomaticBackupStartTime: '02:00'
        CopyTagsToBackups: true
        CopyTagsToVolumes: true
        RootVolumeConfiguration:
          NfsExports:
            - ClientConfigurations:
                - Clients: '*'
                  Options:
                    - rw
                    - sync
                    - no_root_squash
          DataCompressionType: ZSTD
          ReadOnly: false
          RecordSizeKiB: 128
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-fsx-openzfs'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Purpose
          Value: Shared web content storage

  # ========================================
  # S3 Buckets
  # ========================================

  # Drupal/WordPress Media Uploads
  MediaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${EnvironmentName}-drupal-media-${BucketSuffix}'
      VersioningConfiguration:
        Status: !If [S3VersioningEnabled, Enabled, Suspended]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: AbortIncompleteMultipartUpload
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-drupal-media-${BucketSuffix}'
        - Key: Environment
          Value: !Ref EnvironmentName

  # Backups and Logs
  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${EnvironmentName}-backups-${BucketSuffix}'
      VersioningConfiguration:
        Status: !If [S3VersioningEnabled, Enabled, Suspended]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToGlacier
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: GLACIER
          - Id: ExpireOldBackups
            Status: Enabled
            ExpirationInDays: 90
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-backups-${BucketSuffix}'
        - Key: Environment
          Value: !Ref EnvironmentName

  # Image Builder Scripts and Artifacts
  ImageBuilderBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${EnvironmentName}-image-builder-${BucketSuffix}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-image-builder-${BucketSuffix}'
        - Key: Environment
          Value: !Ref EnvironmentName

  # ========================================
  # SSM Parameters (for easy reference by instances)
  # ========================================

  FSxDNSParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${EnvironmentName}/fsx/dns-name'
      Description: FSx OpenZFS DNS name for mounting
      Type: String
      Value: !GetAtt FSxFileSystem.DNSName
      Tags:
        Environment: !Ref EnvironmentName

  FSxMountNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${EnvironmentName}/fsx/mount-name'
      Description: FSx OpenZFS root volume mount name
      Type: String
      Value: !GetAtt FSxFileSystem.RootVolumeId
      Tags:
        Environment: !Ref EnvironmentName

  MediaBucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${EnvironmentName}/s3/media-bucket'
      Description: S3 bucket name for Drupal/WordPress media
      Type: String
      Value: !Ref MediaBucket
      Tags:
        Environment: !Ref EnvironmentName

  BackupBucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${EnvironmentName}/s3/backup-bucket'
      Description: S3 bucket name for backups
      Type: String
      Value: !Ref BackupBucket
      Tags:
        Environment: !Ref EnvironmentName

  ImageBuilderBucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${EnvironmentName}/s3/image-builder-bucket'
      Description: S3 bucket name for Image Builder artifacts
      Type: String
      Value: !Ref ImageBuilderBucket
      Tags:
        Environment: !Ref EnvironmentName

Outputs:
  FSxFileSystemId:
    Description: FSx file system ID
    Value: !Ref FSxFileSystem
    Export:
      Name: !Sub '${EnvironmentName}-fsx-filesystem-id'

  FSxDNSName:
    Description: FSx DNS name for NFS mounting
    Value: !GetAtt FSxFileSystem.DNSName
    Export:
      Name: !Sub '${EnvironmentName}-fsx-dns-name'

  FSxRootVolumeId:
    Description: FSx root volume ID (mount name)
    Value: !GetAtt FSxFileSystem.RootVolumeId
    Export:
      Name: !Sub '${EnvironmentName}-fsx-root-volume-id'

  FSxMountCommand:
    Description: NFS mount command for /var/www
    Value: !Sub 'mount -t nfs -o nfsvers=4.1 ${FSxFileSystem.DNSName}:/fsx /var/www'
    Export:
      Name: !Sub '${EnvironmentName}-fsx-mount-command'

  MediaBucketName:
    Description: S3 bucket name for media uploads
    Value: !Ref MediaBucket
    Export:
      Name: !Sub '${EnvironmentName}-media-bucket-name'

  BackupBucketName:
    Description: S3 bucket name for backups
    Value: !Ref BackupBucket
    Export:
      Name: !Sub '${EnvironmentName}-backup-bucket-name'

  ImageBuilderBucketName:
    Description: S3 bucket name for Image Builder
    Value: !Ref ImageBuilderBucket
    Export:
      Name: !Sub '${EnvironmentName}-image-builder-bucket-name'

# License: GPL-2.0-or-later
# Copyright (C) 2026 The Worx Company
# Author: Kurt Vanderwater <kurt@worxco.net>
